name: Check solutions

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Check
        run: go test ./...
